port: 3000

redis:
  host: localhost
  port: 6379
  db: 0
  password: P@ssw0rd
  expiry:
    item: 36000
    configuration: 36000
    state: 36000
    city: 36000
    floor: 36000
    distance: 36000
    config_setting: 36000
    fvp: 36000
    default_value: 36000
    store: 36000
    user: 36000

jwt:
  secret_key: "<onboard_app_token_secret>"
  refresh_secret_key: "<onboard_app_refersh_token_secret>"
  token_life: '8h'
  refresh_token_life: '24h'
  expiry_hours: 8
  caching: true

db:
  host: localhost
  port: 3306
  username: root
  password: root
  name: onboard


logging:
  level: debug
  # colorize the output on console
  colorize: true
  #     # dirname: './logs'
  filename: 'Onboard-Server-%DATE%.log'
  datePattern: 'YYYY-MM-DD-HH'
  maxSize: '20m'

IP_request_limit:
  max_limit: 1000
  rate_limit_minute: 1
