export const BLOG_REDUX_ACCESS_KEY = {
    INPUT: 'INPUT', 
    OUTLINE: 'OUTLINE',
    SECTION_POINT: 'SECTION_POINT',
    CONTENT: 'CONTENT',
    TITLE: 'TITLE',
    CONTENT_TYPE: 'CONTENT_TYPE',
    LAST_GENERATION_PAGE: 'LAST_GENERATION_PAGE',
    TEMPLATE_TYPE: ''
}

export const TEMPLATE_TYPE = {
    BLOG: 'BLOG', 
    LINKEDIN: 'LINKEDIN',
    SHORT_FORM: 'SHORT_FORM',
    EMAIL: 'EMAIL',
    GOOGLE: 'GOOGLE'
}
